### PR TITLE
Sphinx Docs w/MyST Markdown 

### PR DESCRIPTION
**Pull request by tbsexton**
**WIP** Solves #56

- [MyST](https://myst-parser.readthedocs.io/en/latest/intro.html) provides an excellent way to use markdown in sphinx
- started out with [pydata](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html) theme, though jupyter-book or Furo could be simpler/nicer (per pydata-theme docs)
- copied `readme.md` to `docs/`, though this should likely be split into several smaller pages/headers.

### CODE REVIEW

**Comment by tbsexton** [comment]
@PhilipVinc Probably a question for another issue, but any chance you guys might consider using a [`python-poetry`](https://python-poetry.org/) based toolchain to manage `pyproject.toml`? Makes life a bit easier re: dev dependencies, environments, and deployment.

**Comment by PhilipVinc** [comment]
let's discuss in #58

**Comment by wesselb** [comment]
@tbsexton and @PhilipVinc, sorry for again the super slow reply. I've just gotten back from holidays. :)

Another alternative would be to use a [Jupyter Book](https://jupyterbook.org/en/stable/intro.html) for the documentation, and split things up a bit nicer in chapters, only keeping essential information in `README.md`. I've used a Jupyter Book once before, and it feels a lot simpler than Sphinx. Note that Jupter Book also supports MyST. How would you feel about this option?

**Comment by wesselb** [comment]
Ok, those are some solid arguments! I'm convinced. Let's go for Sphinx + Sphinx Book theme then, built by readthedocs. @tbsexton is this something you'd also be happy with?

**Comment by tbsexton** [comment]
Just to reiterate, `jupyter-book` _is_ sphinx, plus a little sugar. But all sphinx plugins (at least, that I've used, though I tend to use `mkdocs-material` more) will work just fine with jupyter book. 

Jupyter book is basically a customized version of the `pydata` sphinx theme I already selected, plus a dependency on `myst` (which I've also added), and `myst-nb` (which adds jupyter support). 

As I linked before, the [pydata theme devs recommend](https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html) using either `furo` or `jupyter-book` if you want to use the left sidebar more (which I do like, fwiw). The difference between those being: do you want to write your docs in myst/jupyter _notebook_ files, or plain md/rst with vanilla sphinx directives? Either way, the MyST style can be used (which looks exactly like jupyter-book, just without the interspersed "code cells"/literate programming paradigm integrated). 

See here for more info on [jupyter-book re: sphinx interop](https://jupyterbook.org/en/stable/explain/sphinx.html)

**Comment by tbsexton** [comment]
(if you guys want to see a jupyter-book I've been working on for reference, here's the [WIP repo](https://github.com/tlp-coi/text-data-course), deployment to [gh-pages](https://tlp-coi.github.io/text-data-course/). Note it's all just md files using myst-translated sphinx directives. AND It uses a yaml file instead of a giant conf.py, which, not gonna lie, I'm a huge fan of).

**Comment by wesselb** [comment]
> Just to reiterate, jupyter-book is sphinx, plus a little sugar. 

Whoa. That should've been painfully obvious, but I didn't realise this.

The thing I like about Jupyterbook versus Sphinx is the saner config yaml file compared to the rather messy `conf.py`.

In light that Jupyter Book is Sphinx with extra sugar, and hence compatible with most (all?) Sphinx plugins; and in light that the [Jupyter Book theme](https://jupyterbook.org/en/stable/) basically is the [Sphinx Book theme](https://sphinx-book-theme.readthedocs.io/en/stable/), @PhilipVinc would you be amenable to give Jupyter Book a go? [See also the comparison here.](https://jupyterbook.org/en/stable/explain/sphinx.html)

**Comment by PhilipVinc** [comment]
yep. Good for me

**Comment by wesselb** [comment]
Excellent! I'm happy to set this up, unless anyone else would like to do that.

**Comment by wesselb** [comment]
@tbsexton, @PhilipVinc, I've setup a very basic Jupyter Book and moved the entire README there. How does this look to you? I wasn't entirely sure how to share a preview of the result, so I've just pushed the result to `master`. Happy to revert things if we don't like it.

**Comment by tbsexton** [comment]
It should be relatively easy for me (any of us) to switch over this branch to jupyter-book in no time. I've already started the process of splitting out the big readme into sub-sections in myst notebooks, so it may be worth taking a look at those to see if you like it, on this branch?

**Comment by wesselb** [comment]
@tbsexton, I basically took the splitting into files that you've started here and completed the process. You should be able to view the result [here](wesselb.github.io/plum).

**Comment by tbsexton** [comment]
This has been superseded by `main` and #62

**Pull request closed without merging**
